<?php

namespace App\Controllers;

use App\Libraries\PdfLibrary;

class PdfController extends BaseController
{
    public function generateLocationPdf()
    {
        // Create new PDF document
        $pdf = new PdfLibrary(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

        // Set document information
        $pdf->SetCreator(PDF_CREATOR);
        $pdf->SetAuthor('Your Name');
        $pdf->SetTitle('Laporan Lokasi');
        $pdf->SetSubject('PDF dengan Peta Lokasi');
        $pdf->SetKeywords('PDF, CodeIgniter, TCPDF, Peta, Lokasi');

        // Set default header data
        $pdf->SetHeaderData('', 0, 'LAPORAN LOKASI', 'Generated by CodeIgniter 4');

        // Set header and footer fonts
        $pdf->setHeaderFont(array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
        $pdf->setFooterFont(array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

        // Set default monospaced font
        $pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

        // Set margins
        $pdf->SetMargins(15, 25, 15);
        $pdf->SetHeaderMargin(10);
        $pdf->SetFooterMargin(10);

        // Set auto page breaks
        $pdf->SetAutoPageBreak(TRUE, 25);

        // Set image scale factor
        $pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

        // Add a page
        $pdf->AddPage();

        // Set font
        $pdf->SetFont('helvetica', '', 10);

        // Content
        $html = '
        <h1 style="text-align:center;">LAPORAN LOKASI USAHA</h1>
        <p style="text-align:center;">Dibuat pada: ' . date('d/m/Y H:i:s') . '</p>
        
        <h2>Informasi Umum</h2>
        <table border="1" cellpadding="5">
            <tr>
                <td width="30%"><strong>Nama Lokasi</strong></td>
                <td width="70%">Toko Serba Ada "Maju Jaya"</td>
            </tr>
            <tr>
                <td><strong>Pemilik</strong></td>
                <td>Budi Santoso</td>
            </tr>
            <tr>
                <td><strong>Telepon</strong></td>
                <td>081234567890</td>
            </tr>
            <tr>
                <td><strong>Jenis Usaha</strong></td>
                <td>Retail &amp; Grosir</td>
            </tr>
        </table>
        
        <br><br>
        ';

        $pdf->writeHTML($html, true, false, true, false, '');

        // Data lokasi contoh
        $locations = [
            [
                'latitude' => -6.2088,
                'longitude' => 106.8456,
                'address' => 'Jl. Sudirman No. 123, Jakarta Pusat, DKI Jakarta 10220',
                'name' => 'Kantor Pusat'
            ],
            [
                'latitude' => -6.9147,
                'longitude' => 107.6098,
                'address' => 'Jl. Asia Afrika No. 100, Bandung, Jawa Barat 40111',
                'name' => 'Cabang Bandung'
            ]
        ];

        foreach ($locations as $location) {
            // Tambahkan judul cabang
            $pdf->SetFont('helvetica', 'B', 12);
            $pdf->Cell(0, 10, 'Lokasi: ' . $location['name'], 0, 1, 'L');
            $pdf->Ln(2);

            // Tambahkan peta
            $pdf->addMap(
                $location['latitude'],
                $location['longitude'],
                $location['address']
            );

            // Tambahkan halaman baru untuk lokasi berikutnya
            if ($location !== end($locations)) {
                $pdf->AddPage();
            }
        }

        // Close and output PDF document
        $pdf->Output('laporan_lokasi.pdf', 'I');
    }

    public function generatePdfWithOSM()
    {
        // Create new PDF document
        $pdf = new PdfLibrary(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

        // Set document information
        $pdf->SetCreator(PDF_CREATOR);
        $pdf->SetAuthor('Your Name');
        $pdf->SetTitle('Laporan Lokasi dengan OSM');
        $pdf->SetSubject('PDF dengan Peta OpenStreetMap');

        // Add a page
        $pdf->AddPage();

        // Content
        $html = '
        <h1 style="text-align:center;">LAPORAN LOKASI DENGAN OPENSTREETMAP</h1>
        <p style="text-align:center;">Menggunakan OpenStreetMap untuk menampilkan peta</p>
        ';

        $pdf->writeHTML($html, true, false, true, false, '');

        // Tambahkan peta menggunakan OpenStreetMap
        $pdf->addOSMMap(
            -6.2088,
            106.8456,
            'Jl. Sudirman No. 123, Jakarta Pusat, DKI Jakarta 10220'
        );

        // Close and output PDF document
        $pdf->Output('laporan_osm.pdf', 'I');
    }

    public function customLocationPdf()
    {
        // Ambil data dari POST atau GET
        $latitude = $this->request->getPost('latitude') ?? -6.2088;
        $longitude = $this->request->getPost('longitude') ?? 106.8456;
        $address = $this->request->getPost('address') ?? 'Lokasi tidak ditentukan';

        $pdf = new PdfLibrary();
        $pdf->AddPage();

        // Content
        $html = '
        <h2>Lokasi Custom</h2>
        <p><strong>Alamat:</strong> ' . $address . '</p>
        <p><strong>Koordinat:</strong> ' . $latitude . ', ' . $longitude . '</p>
        ';

        $pdf->writeHTML($html, true, false, true, false, '');
        $pdf->addMap($latitude, $longitude, $address);

        $pdf->Output('lokasi_custom.pdf', 'I');
    }
}
